[project]
name = "dptk"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python==4.13.*",
    "numpy",
    "multiprocess",
    "dejaq",
    "pytest",
]

[project.optional-dependencies]
ultralytics = ["ultralytics"]
fastfifo = ["faster-fifo"]
